### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by pmiossec**
following change of color of same author revisions to light blue instead of yellow

Note: Most of the screenshots are made with "Highlight author revisions" disabled

### CODE REVIEW

**Review by gerhardol — APPROVED** [review]
Compared images only, not where they are used or if other should be updated.
All are at least as good as before.

**Comment by pmiossec** [comment]
> Compared images only, not where they are used or if other should be updated. All are at least as good as before.

The ones in the branch folder explaining merge and rebase would be good to be updated but there are not easy to reproduce because a specific branch pattern and naming must be reproduced (or text updated with new branch name).

But I think it's OK for now...

**Review by RussKie — APPROVED** [review]

**Comment by gerhardol** [comment]
Will merge this

**Comment by RussKie** [comment]
👍

**Pull request merged**
