### PR TITLE
Remove obsolete translation and tx integration

### PR DESCRIPTION
**Pull request by gerhardol**
The doc can be translated, but that has not been updated in several years. The source files has not been pushed to Transifex and the updates have not been pulled. read-the-docs do not generate translations.
The doc is not well maintained and something like Google translate probably do an OK job, so I believe it is better to not translate.

That could be fixed, but I do not get it rolling after some attempts.
Maybe the data could bepulled from Transifex before deletion so it can be restored easily if someone objects.

https://app.transifex.com/git-extensions/git-extensions-manual/languages/

### CODE REVIEW

**Comment by RussKie** [comment]
I will have a look at getting the build rolling.

**Comment by gerhardol** [comment]
> I will have a look at getting the build rolling.

I may have got that rolling after opening this PR, but do we really want translated doc?
Translations need to get built too.

**Comment by RussKie** [comment]
Btw, German and Korena translations are almost at 95%:
image

**Comment by gerhardol** [comment]
> Btw, German and Korena translations are almost at 95%:

For 6 years old translation base.
There are some really dedicated translators.
While the doc has not gotten the love it needs, there are a lot of changes.

The core question is if we want a translation?
I do not think so.

**Comment by RussKie** [comment]
> > Btw, German and Korena translations are almost at 95%:
> 
> For 6 years old translation base. There are some really dedicated translators.

I uploaded several new files yesterday. So, yeah, amazing. Though a lot gets translated automatically.

> The core question is if we want a translation?
> I do not think so.

👍

**Pull request merged**
